### ISSUE TITLE
Use web shared

### ISSUE THREAD

**Issue by Aaron-Junker** [php/web-php#523]
PHP.net uses different files for header and footer then web-shared. This is not really optimal, because when something gets updated here it won't get updated on other pages.

**Comment by derickr** [comment]
This is fixed in https://github.com/php/web-shared/commit/b6ed0a9c95a46d9d1308e0b87f5018d2f3099c2e, not?

**Comment by Aaron-Junker** [comment]
@derickr I'm sorry for the late response. No this is not fixed. What I wanted is to include web shared here as a submodule like in the other repos.
